spring.application.name=bebeconforto

# Banco de dados MySQL na nuvem (Railway)
spring.datasource.url=jdbc:mysql://acela.proxy.rlwy.net:49378/railway?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=UwnBUgAwshfknIjPTqBZXEfRPucUVAIz
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate - Forçando o dialeto do MySQL
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configurações de E-mail (Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=samyraalves20007@gmail.com
spring.mail.password=mopscanygllmcght
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Porta do servidor
server.port=9090